language: ruby
sudo: required
before_install:
  - rm Gemfile.lock || true
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
script:
  - bundle exec rake validate
  - bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.2
env:
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  allow_failures:
    - rvm: 2.2.2
      env: PUPPET_VERSION="~> 4.2.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 4.2.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 4.2.0"
  exclude:
    - rvm: 2.2.2
      env: PUPPET_VERSION="~> 3.8.0"
    - rvm: 2.2.2
      env: PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
