language: ruby
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake validate
  - bundle exec rake spec && bundle exec rake beaker
env:
  - PUPPET_VERSION="~> 2.6.0"
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  allow_failures:
    - env: PUPPET_VERSION="~> 2.6.0"
